const nodemailer = require("nodemailer");
const { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, OWNER_EMAIL } = require("../config/env");

let transporter = null;

if (SMTP_USER && SMTP_PASS) {
  transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: SMTP_PORT,
    secure: SMTP_PORT === 465,
    auth: {
      user: SMTP_USER,
      pass: SMTP_PASS,
    },
  });
  console.log("✅ Nodemailer configured");
} else {
  console.warn("⚠️ SMTP credentials not set — email sending disabled");
}

/**
 * Send email
 * @param {string} to - Recipient email
 * @param {string} subject - Email subject
 * @param {string} html - HTML body
 */
const sendEmail = async (to, subject, html) => {
  if (!transporter) {
    console.warn("⚠️ Email not sent — transporter not configured");
    return null;
  }

  try {
    const info = await transporter.sendMail({
      from: `"Mahakal Tour & Travels" <${SMTP_USER}>`,
      to,
      subject,
      html,
    });
    console.log(`✅ Email sent: ${info.messageId}`);
    return info;
  } catch (error) {
    console.error("❌ Email send error:", error.message);
    return null;
  }
};

/**
 * Send lead report to owner
 * @param {object} reportData - { totalLeads, leadsBySource, topRoutes, leads }
 */
const sendLeadReport = async (reportData) => {
  const { totalLeads, leadsBySource, leads } = reportData;

  const sourceRows = Object.entries(leadsBySource)
    .map(([source, count]) => `<tr><td style="padding:8px;border:1px solid #e2e8f0;">${source}</td><td style="padding:8px;border:1px solid #e2e8f0;text-align:center;">${count}</td></tr>`)
    .join("");

  const leadRows = leads
    .slice(0, 20)
    .map(
      (lead) =>
        `<tr>
          <td style="padding:8px;border:1px solid #e2e8f0;">${lead.name}</td>
          <td style="padding:8px;border:1px solid #e2e8f0;">${lead.phone || "-"}</td>
          <td style="padding:8px;border:1px solid #e2e8f0;">${lead.pickup || "-"} → ${lead.drop || "-"}</td>
          <td style="padding:8px;border:1px solid #e2e8f0;">${lead.source}</td>
          <td style="padding:8px;border:1px solid #e2e8f0;">${new Date(lead.createdAt).toLocaleDateString("en-IN")}</td>
        </tr>`
    )
    .join("");

  const html = `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;">
      <div style="background:linear-gradient(135deg,#ea580c,#d97706);padding:24px;text-align:center;border-radius:12px 12px 0 0;">
        <h1 style="color:white;margin:0;font-size:24px;">📊 Weekly Lead Report</h1>
        <p style="color:#ffedd5;margin:8px 0 0;">Mahakal Tour & Travels</p>
      </div>
      
      <div style="padding:24px;background:#f8fafc;border:1px solid #e2e8f0;">
        <h2 style="color:#0f172a;font-size:18px;">Summary</h2>
        <p style="color:#475569;">Total leads this week: <strong style="color:#ea580c;font-size:20px;">${totalLeads}</strong></p>
        
        <h3 style="color:#0f172a;font-size:16px;margin-top:20px;">Leads by Source</h3>
        <table style="width:100%;border-collapse:collapse;margin-top:8px;">
          <thead>
            <tr style="background:#f1f5f9;">
              <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Source</th>
              <th style="padding:8px;border:1px solid #e2e8f0;text-align:center;">Count</th>
            </tr>
          </thead>
          <tbody>${sourceRows}</tbody>
        </table>

        <h3 style="color:#0f172a;font-size:16px;margin-top:20px;">Recent Leads (Latest 20)</h3>
        <table style="width:100%;border-collapse:collapse;margin-top:8px;font-size:13px;">
          <thead>
            <tr style="background:#f1f5f9;">
              <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Name</th>
              <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Phone</th>
              <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Route</th>
              <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Source</th>
              <th style="padding:8px;border:1px solid #e2e8f0;text-align:left;">Date</th>
            </tr>
          </thead>
          <tbody>${leadRows}</tbody>
        </table>
      </div>
      
      <div style="padding:16px;text-align:center;background:#0f172a;border-radius:0 0 12px 12px;">
        <p style="color:#94a3b8;margin:0;font-size:12px;">Auto-generated by Mahakal Tour & Travels System</p>
      </div>
    </div>
  `;

  return sendEmail(OWNER_EMAIL, `📊 Weekly Lead Report — ${totalLeads} leads this week`, html);
};

module.exports = { sendEmail, sendLeadReport };
